### ISSUE TITLE
ls -N should give indication of truncated output

### ISSUE THREAD

**Issue by inducer** [topydo/topydo#116]
I copy-pasted an `ls` alias from, um, somewhere, and that contained a `-N`. I was quite surprised to figure out that the output I was seeing was truncated. I figure that's a usability issue that's easy to avoid--just output a `...` somewhere (e.g. end of the last line of outptu?) if the output is actually  truncated.

**Comment by inducer** [comment]
For context, I should add that I use `ls` with most-important-last sorting, so `-N` truncating from the front would also be useful, but that's probably a separate (if related) thing.

**Comment by jucor** [comment]
For info, the original `todo.sh` concludes its `ls` output by:
```
--
TODO: 10 of 42 tasks shown
```
Might be worth having?

**Comment by MinchinWeb** [comment]
@jucor : I think it would be worth adding, just no one has gotten around to doing it yet!

**Comment by davesteele** [comment]
Granted, it is buried, but the option is defined in the [TiddlyWiki](https://cdn.rawgit.com/bram85/topydo/master/docs/index.html#ls).

The terse output is in keeping with the Unix philosophy - it makes it easier to set up pipe chains. 

I'd consider a PR with broad(ish) support.
