### ISSUE TITLE
Watch done.txt for recurring tasks completed externally

### ISSUE THREAD

**Issue by cappallo** [topydo/topydo#152]
I suggest you add done.txt as a watched file also, and when altered by an outside program, check it for recurrences and trigger on a task as necessary. This is so completing a task with an external interface, say the todo.txt app on my Android phone, would still be handled as expected.

**Comment by davesteele** [comment]
This would have to monitor todo.txt, in the general case (which would be difficult to handle correctly).

SimpleTask on Android will handle recurrences.
