### ISSUE TITLE
topydo.org is down?

### ISSUE THREAD

**Issue by jason-mehmel** [topydo/topydo#269]
Hey! Just discovered this program, and noticed that Topydo.org is down. A lot of the documentation was there, no? Does anyone have it backed up or saved somewhere?

**Comment by jdckr** [comment]
https://web.archive.org/web/20180831061945/https://cdn.rawgit.com/bram85/topydo/master/doc/Documentation.html

**Comment by adityabhaskar** [comment]
I have hosted a temporary copy too till the original comes up... https://c306.net/t/topydo-docs/

**Comment by jason-mehmel** [comment]
Is there any way to host that copy right in Github somehow?

~Jason
pronouns: he / him / his

jmehmel@gmail.com | www.jasonmehmel.com

**Comment by adityabhaskar** [comment]
> Is there any way to host that copy right in Github somehow?

Github pages would be the simplest thing. But I don't want to host it on my account's github page. 

Ideal scenario would be to create an organisation/account for topydo (similar to [todo.txt](https://github.com/todotxt/todotxt.github.io) ) and publish the documentation there. It would be best though that such an account is opened by @bram85  or with their consent.

**Comment by MinchinWeb** [comment]
Another link, I think to the CDN that was behind the "original" site --> https://cdn.rawgit.com/bram85/topydo/master/docs/index.html

**Comment by uGeek** [comment]
Other link
https://ugeek.github.io/blog/varios/topydo.html

**Comment by davesteele** [comment]
References to topydo.org have been removed in master.

**Comment by SevereOverfl0w** [comment]
It's still referenced in the "about" of the repo btw.
