### ISSUE TITLE
future of this project

### ISSUE THREAD

**Issue by nnako** [topydo/topydo#275]
Hi Bram,

thank you so much for topydo!!! :-)

as the last changes to the source code have been made more than 14 months ago, the home page topydo.org seems to be down for months now (and with it large parts of the user and configuration documentation), and some recent questions have not been answered, yet, I was wondering if this project was currently still under development.

**Could you leave us a word about the current state and you plans concerning topydo?**

There might be possibilities to contribute and maybe you could hand over some features to chosen parts of the community?

Thanks
Nnako

**Comment by p-phillips** [comment]
I tracked Bram down last year to ask about the project.  He is fine but his normal work/life means he doesn't have time to continue with this.  He said that @mruwek may be willing to take over some minimum maintenance of the project.

I still use and love topydo so would be keen to see it being maintained again. 

Are you, @nnako,   interested in maintainership of the project ? I'd be happy to contact Bram again to ask if he was fine with this.

Pete

**Comment by QuarkMuncher** [comment]
@p-phillips  What does it entail being a maintainer?

**Comment by nnako** [comment]
Hi @p-phillips,

indeed, I'd be interested in continuing maintainance of the project. Thanks for the offer. But, in order to have a quick start, I would like to, first, address some of my questions regarding the project. Would it be possible to talk to @bram85 about technical subjects concerning this project, like:

### further structural information
how do the project files connect to each other? which are the core "components" and what technical interfaces are used between them? what is the overall code structure? is there a list of all the dependencies (libraries, environmental conditions,...)? which dependencies and interfaces are critical concerning keeping backwards compatibility with previous versions and user environments?

### concepts for coding
are there speific coding concepts and constructs which have been followed so far? what should be considered when creating new features or changing existing ones? have any commenting concepts been used so far which should be continued?

### concepts for testing
how does the test framework work for this project within GitHub in detail? where to add test cases and modify them, and what to further consider regarding testing e.g. testing for different systems in various execution environments?

### user web site
how to get it up and running again in order to provide detailed user information? have there been efforts in keeping code and documentation synchronized? what about auto-documentation from code itself? at least in parts? have there been made some approaches, yet?

### further roadmap
are there maybe already plans for next steps in development of topydo? Some "hidden" todo items? or some things which would be great to achieve in order to fill a specific application gap or provide a often-requested application interface?

There would be a lot more questions, though ;-)

Thanks.
Nnako

**Comment by p-phillips** [comment]
Hi Nnako

I'm going to try to link you up with Bram so you can chat this through.

Pete

**Comment by p-phillips** [comment]
Hi Nnako - Bram has agreed I can share his email address with you so you can deal with this without me acting as an intermediary.  Email me on:  peteJUNKATphilfam.co.uk (replacing the capitals with the at sign)

**Comment by shawnaxsom** [comment]
@p-phillips @nnako I'd be interested in being a maintainer as well. Did anything become of this?

**Comment by p-phillips** [comment]
Hi Shawn.

I did send an introductory email but heard nothing since.

I've sent you Bram's contact address.

Pete

**Comment by shawn-pe** [comment]
Thanks! I've sent him an email, I'll see if I can get a response.

**Comment by nnako** [comment]
Hi @p-phillips,

thanks for trying to establish a direct contact to Bram. My direct message to him (using the address I was given) has not been responded, yet. Maybe the content didn't satisfy ;-) . still, at least a short note would be appreciated.

Nnako

**Comment by p-phillips** [comment]
Hi guys. OK - I will give Bram a nudge.
Pete

**Comment by p-phillips** [comment]
Just to update you I've messaged Bram to explain that two of you are trying to contact him about taking on this project.

**Comment by shawnaxsom** [comment]
I'm assuming there hasn't been an update from Bram. That's unfortunate.

The project is GPLed, so maybe we will have to consider a fork if Bram doesn't respond. I've been starting a fork of ([Todour](https://github.com/SverrirValgeirsson/Todour)) dubbed ([Inizio](https://github.com/shawnaxsom/inizio)) for Mac desktop todo.txt editing as well, I'd be happy to contribute to both.

**Comment by p-phillips** [comment]
I'll try Bram again.  I think he is very busy hence being unable to maintain this.  Leave it with me to have another go.

**Comment by davesteele** [comment]
I just came here to address this issue, and see that it is already being discussed.

I've been a happy user for about two years, and, as a Debian Developer, I would like to package this and todo.txt for inclusion with Debian (A personal goal is to make [this patch](https://github.com/davesteele/topydo/commit/fafee24beb4718f375a921f3b4772c5fea37d7ac) unnecessary for my purposes).

Before packaging can happen, this repository needs some maintenance. If Debian keeps to its past schedule, the freeze for the next stable release will happen in the first half of next year. In order to get this into Debian stable before 2023, things would need to start happening soon.

I am willing to help with upstream maintenance - I have a number of outstanding [pull requests](https://github.com/bram85/topydo/pulls/davesteele).

**Comment by p-phillips** [comment]
Morning all.  

Had contact with Bram and he is willing to transfer ownership of the repo. Does anyone know how to do that?

Bram said he hopes to be able to chip in to the discussion on github in next few days anyway.

**Comment by shawnaxsom** [comment]
@p-phillips Great!

Ownership transfer is simple enough. When he's signed in, "Transfer ownership" is one of the "Danger Zone" action buttons that are found on the main Options tab of the repo's Settings page, as described here:

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account

**Comment by p-phillips** [comment]
Do you guys need to make a decision as to who will be the owner of the repo then ?

**Comment by shawnaxsom** [comment]
Yeah, we haven't discussed ownership.

I'm happy to own it; others can speak up here too if they're interested. Or we might be able to create a GitHub organization.

**Comment by davesteele** [comment]
There is enough interest here that I would recommend an organization. Questions of ownership/admin access remain.

Once processes are worked out, I'd like to be able to add value via commit access.

**Comment by davesteele** [comment]
@p-phillips, I'd vote that you should go ahead and make the organization, and put the three of us on an admin team. We can figure out the rest.

**Comment by bram85** [comment]
Author here. My apologies for the wait, real life really got me so I have no time to maintain topydo anymore. I'm thankful for your interest to keep the project alive.

I think creating an organization is a good idea, I went ahead and created one under github.com/topydo . I have yet to transfer this repo to it.

Having me as the sole owner is obviously not a good idea, so I'd like to have one more username becoming an owner as well who's willing to support the maintenance over a longer period of time. Other volunteers who would like to maintain the project may become an admin within this organization. For the admins I suppose it would be the participants in this issue. Any volunteer for organization ownership?

Again, thank you all for your interest in topydo and (valid) concerns of its future.

**Comment by davesteele** [comment]
I'm willing to make a longer term commitment for support. If you're looking for one name, @p-phillips should have first right of refusal - he's done the work as of late.

**Comment by bram85** [comment]
OK, I invited @davesteele to become co-owner and transferred the repository to the topydo organization.

While being owner, I'll stay on the sideline and put my trust in the community to maintain the project. To me the project is feature complete, it reached the point I envisioned about 6 years ago.

Good luck!

**Comment by davesteele** [comment]
Thank you for the honor, @bram85. I look forward to working to get this useful porject in front of a wider audience.
