### ISSUE TITLE
"raise ... from" syntax errors in Python 3.9

### ISSUE THREAD

**Issue by davesteele** [topydo/topydo#283]
There are syntax errors being thrown during the build step. Running on Debian unstable, Python 3.9.1rc1.

      File "/usr/share/topydo/topydo/lib/Config.py", line 502
        raise ConfigError(str(perr)) from perr
                                        ^
    SyntaxError: invalid syntax
    
      File "/usr/share/topydo/topydo/lib/TodoListBase.py", line 109
        raise InvalidTodoException from te
                                      ^
    SyntaxError: invalid syntax
    
      File "/usr/share/topydo/topydo/lib/Command.py", line 75
        raise InvalidCommandArgument from ie
                                        ^
    SyntaxError: invalid syntax
    
      File "/usr/share/topydo/topydo/Commands.py", line 96
        raise ConfigError(alias_map[p_alias]) from ve
                                                 ^
    SyntaxError: invalid syntax

**Comment by mruwek** [comment]
That's interesting. I can't see any official syntax change in [official documentation for 3.9](https://docs.python.org/3.9/tutorial/errors.html#exception-chaining)

**Comment by davesteele** [comment]
Agreed. This is a function of my build. It is still trying 2.7 for some reason.
