### ISSUE TITLE
configure possibility not to use creation dates

### ISSUE THREAD

**Issue by vojtapolasek** [topydo/topydo#288]
Hello,
would it be possible to optionally DO NOT put creation date in front of the task while creating it? I imagine this could be configured.

**Comment by davesteele** [comment]
I promise to promptly consider PRs.

**Comment by bram85** [comment]
It's an option already, see https://cdn.rawgit.com/bram85/topydo/master/docs/index.html#ConfigAutoCreation

**Comment by vojtapolasek** [comment]
ooooh, I was looking there but I apparently overlooked it. Thank you so much.
