### ISSUE TITLE
'pip3 install topydo[columns]' (and prompt) giving no matches found: topydo[columns]

### ISSUE THREAD

**Issue by MostHated** [topydo/topydo#296]
Hey there,
    Am I doing something incorrectly? It is not seeing prompt or columns being available?

![](https://i.imgur.com/LMbimCy.png)

Thanks,
-MH

**Comment by bram85** [comment]
Please use single quotes around topydo[columns] and topydo[prompt] because now the square brackets are interpreted by the shell.
