### ISSUE TITLE
Doc link not viewable

### ISSUE THREAD

**Issue by clach04** [topydo/topydo#301]
https://github.com/topydo/topydo/blob/master/README.md?plain=1#L70 link to https://cdn.rawgit.com/bram85/topydo/master/docs/index.html ends up viewing html source, not html/wiki

**Comment by davesteele** [comment]
Looks like they changed the web behavior. 

The deb install adds this file as */usr/share/doc/topydo/docs/index.html*

**Comment by 00sapo** [comment]
Wouldn't it be possible to distribute it in the python package and add a command "docs" that opens it in the browser?

**Comment by davesteele** [comment]
Sure.

**Comment by JohannesPertl** [comment]
Any other way to view the documentation? This can't be hard to fix right? It's kinda hard to start with this tool, if the official wiki is down..

**Comment by clach04** [comment]
Alternative would be GitHub Pages

**Comment by bram85** [comment]
topydo.org points to the documentation, I don't really think this is a real issue anymore.
