### ISSUE TITLE
Custom commands and external scripts

### ISSUE THREAD

**Issue by 00sapo** [topydo/topydo#304]
Is it possible to run external scripts or custom hooks? 

In the CLI mode, it is easy to pipe them into a system command, however with a special syntax in the prompt mode, we would allow using them both in the prompt and column mode (via key mapping for instance). An idea could be that everything coming after a `!` is used to create a `Popen` object, and the output of the topydo's subcommand is passed via `Popen.communicate`. 

I can create a pull-request if you tell me where such a code should be introduced

**Comment by 00sapo** [comment]
Reasoning about it, maybe it's simply better to give the user the ability to define custom commands that run custom python functions

**Comment by davesteele** [comment]
In Debian, topydo depends on todo.txt-base, which provides such a capability using a wrapper.

**Comment by 00sapo** [comment]
Could you be a little more precise? Is there any documentation about it? Can we set up keybindings from the column view?

**Comment by 00sapo** [comment]
Still some question: what if my command should print some output? While in column mode, can we reconstruct the columns, e.g. something like `:redraw` in vim?

**Comment by davesteele** [comment]
It just allows calling a todo.txt-modifying process before or after the cli topydo runs.
