### ISSUE TITLE
Documentation wiki can't be displayed by GitHub

### ISSUE THREAD

**Issue by rptb1** [topydo/topydo#309]
https://github.com/topydo/topydo/blob/master/docs/index.html (as linked from the readme) says:
> (Sorry about that, but we can’t show files that are this big right now.)

Note that this is also true in the "new code view" beta.

**Comment by davesteele** [comment]
The document is a TiddlyWiki - looking at it's source would not be that useful. There is a [link](https://topydo.org/) to a live version in the README.

**Comment by rptb1** [comment]
When I click on the link to the documentation in the README displayed at https://github.com/topydo/topydo , it takes me to https://topydo.org/ but that redirects to https://github.com/topydo/topydo/blob/master/docs/index.html which can't be displayed (see above).
